# Generated by Django 2.1.3 on 2019-04-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentdetail',
            name='days_to_complete_course',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deploymentdetail',
            name='deliverable_id',
            field=models.IntegerField(default=0),
        ),
    ]
