# Generated by Django 2.1.3 on 2019-04-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployment_detail', '0002_auto_20190415_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentdetail',
            name='deployment_status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
