# Generated by Django 2.1.3 on 2019-04-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('project_lead', models.CharField(max_length=50)),
                ('project_code', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('course_duration', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=300)),
                ('content_complete_date', models.DateTimeField()),
                ('record_date', models.DateTimeField()),
                ('processing_complete_date', models.DateTimeField()),
                ('post_processing_complete_date', models.DateTimeField()),
                ('target_deploy_date', models.DateTimeField()),
            ],
        ),
    ]
