# Generated by Django 2.1.3 on 2019-04-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverable_detail', '0002_auto_20190414_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='deliverable_id',
        ),
    ]
